version: '3.3'

networks:
  lega:
    driver: overlay
  cega_cega:
    external: true

services:

  mq:
    image: rabbitmq:3.6.14-management
    hostname: mq
    networks:
      - lega
      - cega_cega
    ports:
      - "15672:15672"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
    environment:
      - CEGA_CONNECTION
    configs:
      - source: lega.defs.json
        target: /etc/rabbitmq/defs.json
      - source: lega.rabbitmq.config
        target: /etc/rabbitmq/rabbitmq.config
      - source: lega.entrypoint.sh
        target: /usr/bin/ega-entrypoint.sh
    entrypoint: ["/bin/bash", "/usr/bin/ega-entrypoint.sh"]
    command: ["rabbitmq-server"]

  db:
    image: postgres:9.6
    hostname: db
    networks:
      - lega
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
    environment:
      - DB_INSTANCE=db
      - POSTGRES_DB=lega
      - POSTGRES_USER=lega
      - POSTGRES_PASSWORD
    configs:
      - source: db.sql
        target: /docker-entrypoint-initdb.d/ega.sql

  inbox:
    image: nbisweden/ega-mina-inbox:latest
    hostname: ega-inbox
    networks:
      - lega
      - cega_cega
    ports:
      - "2222:2222"
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
    depends_on:
      - mq
    environment:
      - CEGA_ENDPOINT
      - CEGA_ENDPOINT_CREDS
    volumes:
      - inbox:/ega/inbox

  id-mapper:
    image: nbisweden/ega-base:latest
    networks:
      - lega
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
    depends_on:
      - db
      - mq
    configs:
      - source: conf.ini
        target: /etc/ega/conf.ini
    entrypoint: ["gosu", "lega", "ega-id-mapper"]

  ingest:
    image: nbisweden/ega-base:latest
    networks:
      - lega
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
    depends_on:
      - db
      - mq
      - s3
    environment:
      - S3_ACCESS_KEY
      - S3_SECRET_KEY
    volumes:
       - inbox:/ega/inbox
    configs:
      - source: conf.ini
        target: /etc/ega/conf.ini
    entrypoint: ["gosu", "lega", "ega-ingest"]

  keys:
    image: cscfi/ega-keyserver:latest
    hostname: keys
    networks:
      - lega
      - cega_cega
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
    environment:
      - SPRING_PROFILES_ACTIVE=no-oss
      - EGA_KEY_PATH=/etc/ega/pgp/ega.sec,/etc/ega/pgp/ega2.sec
      - EGA_KEYPASS_PATH=/etc/ega/pgp/ega.sec.pass,/etc/ega/pgp/ega2.sec.pass
      - EGA_SHAREDPASS_PATH=/etc/ega/pgp/ega.shared.pass
      - EGA_PUBLICKEY_URL=
      - EGA_LEGACY_PATH=
    configs:
      - source: ega.sec
        target: /etc/ega/pgp/ega.sec
      - source: ega2.sec
        target: /etc/ega/pgp/ega2.sec
      - source: ega.sec.pass
        target: /etc/ega/pgp/ega.sec.pass
      - source: ega2.sec.pass
        target: /etc/ega/pgp/ega2.sec.pass
      - source: ega.shared.pass
        target: /etc/ega/pgp/ega.shared.pass

  verify:
    image: nbisweden/ega-base:latest
    hostname: verify
    networks:
      - lega
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
    depends_on:
      - db
      - mq
      - keys
      - s3
    environment:
      - LEGA_PASSWORD
      - S3_ACCESS_KEY
      - S3_SECRET_KEY
    configs:
      - source: conf.ini
        target: /etc/ega/conf.ini
    entrypoint: ["gosu", "lega", "ega-verify"]

  res:
    image: cscfi/ega-res:latest
    hostname: res
    networks:
      - lega
    ports:
      - "8081:8080"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
    depends_on:
      - s3
      - keys
    environment:
      - SPRING_PROFILES_ACTIVE=no-oss,LocalEGA
      - EGA_EGA_EXTERNAL_URL=
      - EGA_EGA_CRAM_FASTA_A=
      - EGA_EGA_CRAM_FASTA_B=
      - EGA_EBI_FIRE_URL=
      - EGA_EBI_FIRE_ARCHIVE=
      - EGA_EBI_FIRE_KEY=
      - SERVICE_ARCHIVE_CLASS=
      - EGA_SHAREDPASS_PATH=/etc/ega/pgp/ega.shared.pass
      - EGA_EBI_AWS_ENDPOINT_URL=http://s3:9000
      - EGA_EBI_AWS_ACCESS_KEY=
      - EGA_EBI_AWS_ACCESS_SECRET=
      - EGA_EBI_AWS_ENDPOINT_REGION=
    configs:
      - source: ega.shared.pass
        target: /etc/ega/pgp/ega.shared.pass

  s3:
    image: minio/minio:latest
    hostname: s3
    networks:
      - lega
    ports:
      - "9000:9000"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
    environment:
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY
    volumes:
      - s3:/data
    command: server /data

  portainer:
    image: portainer/portainer:latest
    ports:
        - "30000:9000"
    command: --no-auth
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data

volumes:
  inbox:
  s3:
  portainer:

configs:
  lega.defs.json:
    external: true
  lega.rabbitmq.config:
    external: true
  lega.entrypoint.sh:
    external: true
  db.sql:
    external: true
  conf.ini:
    external: true
  keys.ini.enc:
    external: true
  ssl.cert:
    external: true
  ssl.key:
    external: true
  ega.sec:
    external: true
  ega2.sec:
    external: true
  ega.sec.pass:
    external: true
  ega2.sec.pass:
    external: true
  ega.shared.pass:
    external: true