version: '3.3'

networks:

  cega:
    external: true

services:

  cega-mq:
    image: rabbitmq:3.6.14-management
    hostname: cega-mq
    networks:
      - cega
    ports:
      - "15670:15672"
      - "5672:5672"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
    configs:
      - source: cega.defs.json
        target: /etc/rabbitmq/defs.json
      - source: cega.rabbitmq.config
        target: /etc/rabbitmq/rabbitmq.config

  cega-users:
    image: nbisweden/ega-base:latest
    hostname: cega-users
    networks:
      - cega
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
    environment:
      - LEGA_INSTANCES
      - CEGA_REST_lega_PASSWORD
    configs:
      - source: users.html
        target: /cega/users.html
      - source: server.py
        target: /cega/server.py
      - source: john.yml
        target: /cega/users/lega/john.yml
      - source: jane.yml
        target: /cega/users/lega/jane.yml
    command: ["python3.6", "/cega/server.py"]

configs:
  cega.defs.json:
    external: true
  cega.rabbitmq.config:
    external: true
  eureka.py:
    external: true
  server.py:
    external: true
  users.html:
    external: true
  john.yml:
    external: true
  jane.yml:
    external: true