version: '3.3'

services:

  logzio:
    image: logzio/logzio-docker
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
    environment:
      - LOGZIO_TOKEN
      - LOGZIO_ZONE=us
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["--no-stats", "--no-dockerEvents", "-a", "stack=public", "-a", "rev=${GIT_COMMIT_SHORT}", "-a", "build=${BUILD_NUMBER}"]

  mq:
    image: rabbitmq:3.7.8-management
    ports:
      - "4369:4369"
      - "5672:5672"
      - "15672:15672"
      - "35672-35682:35672-35682"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
    environment:
      - CEGA_CONNECTION
    configs:
      - source: lega-public.defs.json
        target: /etc/rabbitmq/defs.json
      - source: lega-public.rabbitmq.config
        target: /etc/rabbitmq/rabbitmq.config
      - source: lega-public.entrypoint.sh
        target: /usr/bin/ega-entrypoint.sh
    entrypoint: ["/bin/bash", "/usr/bin/ega-entrypoint.sh"]
    command: ["rabbitmq-server"]

  inbox:
    image: nbisweden/ega-mina-inbox:latest
    ports:
      - "2222:2222"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
    depends_on:
      - mq
    environment:
      - CEGA_ENDPOINT
      - CEGA_ENDPOINT_CREDS
      - S3_ACCESS_KEY=${INBOX_S3_ACCESS_KEY}
      - S3_SECRET_KEY=${INBOX_S3_SECRET_KEY}
      - S3_ENDPOINT
      - USE_SSL=false
    volumes:
      - inbox:/ega/inbox

volumes:
  inbox:

configs:
  lega-public.defs.json:
    external: true
  lega-public.rabbitmq.config:
    external: true
  lega-public.entrypoint.sh:
    external: true
