version: '3.3'

services:

  mq:
    image: rabbitmq:3.6.14-management
    ports:
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"
      - "33672:33672"
      - "33673:33673"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
    environment:
      - RABBITMQ_DIST_PORT=25672
      - RABBITMQ_CTL_DIST_PORT_MIN=33672
      - RABBITMQ_CTL_DIST_PORT_MAX=33673
      - CEGA_CONNECTION
    configs:
      - source: lega-public.defs.json
        target: /etc/rabbitmq/defs.json
      - source: lega-public.rabbitmq.config
        target: /etc/rabbitmq/rabbitmq.config
      - source: lega-public.entrypoint.sh
        target: /usr/bin/ega-entrypoint.sh
    entrypoint: ["/bin/bash", "/usr/bin/ega-entrypoint.sh"]
    command: ["rabbitmq-server"]

  inbox:
    image: nbisweden/ega-mina-inbox:latest
    ports:
      - "2222:2222"
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
    depends_on:
      - mq
    environment:
      - CEGA_ENDPOINT
      - CEGA_ENDPOINT_CREDS
    volumes:
      - inbox:/ega/inbox

  mediator-client:
    image: uiobmi/mediator.client:latest
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
    depends_on:
      - mq
    environment:
      - BROKER_HOST=mq
      - MEDIATOR_SERVER

volumes:
  inbox:
    external: true

configs:
  lega-public.defs.json:
    external: true
  lega-public.rabbitmq.config:
    external: true
  lega-public.entrypoint.sh:
    external: true
  conf.ini:
    external: true
  keys.ini.enc:
    external: true
  ssl.cert:
    external: true
  ssl.key:
    external: true
  ega.sec:
    external: true
  ega2.sec:
    external: true
  ega.sec.pass:
    external: true
  ega2.sec.pass:
    external: true
  ega.shared.pass:
    external: true
