version: '3.3'

services:

  mq:
    image: rabbitmq:3.7.8-management
    ports:
      - "4369:4369"
      - "5672:5672"
      - "15672:15672"
      - "35672-35682:35672-35682"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
    environment:
      - CEGA_CONNECTION
    configs:
      - source: lega-public.defs.json
        target: /etc/rabbitmq/defs.json
      - source: lega-public.rabbitmq.config
        target: /etc/rabbitmq/rabbitmq.config
      - source: lega-public.entrypoint.sh
        target: /usr/bin/ega-entrypoint.sh
    entrypoint: ["/bin/bash", "/usr/bin/ega-entrypoint.sh"]
    command: ["rabbitmq-server"]

  inbox:
    image: nbisweden/ega-mina-inbox:latest
    ports:
      - "2222:2222"
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
    depends_on:
      - mq
    environment:
      - CEGA_ENDPOINT
      - CEGA_ENDPOINT_CREDS
    volumes:
      - inbox:/ega/inbox

  mediator-client:
    image: uiobmi/mediator.client:latest
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
    depends_on:
      - mq
    environment:
      - BROKER_HOST=mq
      - QUEUES=files,stableIDs
      - MEDIATOR_SERVER

volumes:
  inbox:
    external: true

configs:
  lega-public.defs.json:
    external: true
  lega-public.rabbitmq.config:
    external: true
  lega-public.entrypoint.sh:
    external: true
