version: '3.3'

services:

  logzio:
    image: logzio/logzio-docker
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
    environment:
      - LOGZIO_TOKEN
      - LOGZIO_ZONE=us
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["--no-stats", "--no-dockerEvents", "-a", "stack=public", "-a", "rev=${GIT_COMMIT_SHORT}", "-a", "build=${BUILD_NUMBER}", "-a", "env=${ENV}"]

  mq:
    image: ${PUBLIC_BROKER_SERVICE}
    ports:
      - "5671:5671"
      - "15671:15671"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
    environment:
      - USER_NAME=admin
      - PASSWORD_HASH=4tHURqDiZzypw0NTvoHhpn8/MMgONWonWxgRZ4NXgR8nZRBz
      - PRIVATE_CONNECTION
      - CEGA_CONNECTION
    configs:
      - source: mq.cert
        target: /etc/rabbitmq/ssl.cert
      - source: mq.key
        target: /etc/rabbitmq/ssl.key
      - source: CA.cert
        target: /etc/rabbitmq/CA.cert

  inbox:
    image: ${INBOX_SERVICE}
    ports:
      - "2222:2222"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
    depends_on:
      - mq
    environment:
      - CEGA_ENDPOINT
      - CEGA_ENDPOINT_CREDS
      - S3_ACCESS_KEY=${INBOX_S3_ACCESS_KEY}
      - S3_SECRET_KEY=${INBOX_S3_SECRET_KEY}
      - S3_ENDPOINT
      - BROKER_USERNAME=admin
      - INBOX_JKS_PATH=/etc/ega/inbox.jks
      - INBOX_JKS_PASSWORD
      - LOGGING_LEVEL_ROOT=OFF
    configs:
      - source: CA.cert
        target: /usr/local/share/ca-certificates/CA.cert
      - source: inbox.jks
        target: /etc/ega/inbox.jks
    volumes:
      - inbox:/ega/inbox

volumes:
  inbox:


configs:
  CA.cert:
    external: true
  mq.cert:
    external: true
  mq.key:
    external: true
  inbox.jks:
    external: true
