version: '3.3'

services:

  logzio:
    image: logzio/logzio-docker
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
    environment:
      - LOGZIO_TOKEN
      - LOGZIO_ZONE=us
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["--no-stats", "--no-dockerEvents", "-a", "stack=public", "-a", "rev=${GIT_COMMIT_SHORT}", "-a", "build=${BUILD_NUMBER}", "-a", "env=${ENV}"]

  mq:
    image: uiobmi/localega-broker:public
    ports:
      - "5672:5672"
      - "15672:15672"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
    environment:
      - USER_NAME=admin
      - PASSWORD_HASH=4tHURqDiZzypw0NTvoHhpn8/MMgONWonWxgRZ4NXgR8nZRBz
      - PRIVATE_CONNECTION
      - CEGA_CONNECTION

  inbox:
    image: nbisweden/ega-mina-inbox:latest
    ports:
      - "2222:2222"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
    depends_on:
      - mq
    environment:
      - CEGA_ENDPOINT
      - CEGA_ENDPOINT_CREDS
      - S3_ACCESS_KEY=${INBOX_S3_ACCESS_KEY}
      - S3_SECRET_KEY=${INBOX_S3_SECRET_KEY}
      - S3_ENDPOINT
      - BROKER_USERNAME=admin
      - USE_SSL=false
    volumes:
      - inbox:/ega/inbox

volumes:
  inbox:
